[package]
name = "rusty_v8"
version = "0.0.3"
description = "Rust bindings to V8"
readme = "README.md"
authors = ["the Deno authors"]
license = "MIT"
edition = "2018"
repository = "https://github.com/denoland/rusty_v8"

exclude = [
 "buildtools/third_party/libc++/trunk/test/",
 "buildtools/third_party/libc++abi/trunk/test/",
 "v8/ChangeLog",
 "v8/test/cctest/*.cc",
 "v8/test/cctest/compiler/",
 "v8/test/cctest/heap/",
 "v8/test/cctest/interpreter/",
 "v8/test/cctest/wasm/",
 "v8/test/mjstest/*.js",
 "v8/test/mjstest/asm/",
 "v8/test/mjstest/compiler/",
 "v8/test/mjstest/es6/",
 "v8/test/mjstest/harmony/",
 "v8/test/mjstest/regress/",
 "v8/test/mjstest/wasm/",
 "v8/test/webkit/*.js",
 "v8/test/webkit/*.txt",
 "v8/test/webkit/fast/",
 "v8/tools/profview/",
 "v8/tools/profviz/",
]

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.65"

[build-dependencies]
cargo_gn = "0.0.13"
which = "3.0.0"
