[target.aarch64-linux-android]
image = "cross:aarch64-linux-android-0.2.1"

[build.env]
passthrough = [
    "V8_FROM_SOURCE",
    "SCCACHE_ERROR_LOG",
    "SCCACHE_LOG",
    "SCCACHE_DIR",
    "SCCACHE_IDLE_TIMEOUT"
]
