name: Update V8

on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Setup Git user
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git config --local user.password ${{ secrets.GITHUB_TOKEN }}
          echo "GIT_USER=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - run: deno run -A ./tools/auto_update_v8.ts
          